rules {
  SMG_QUARANTINE_DISCARD {
    action = "discard";
    expression = "SMG_QUARANTINED";
    require_action = ["no action", "add header", "rewrite subject", "greylist", "soft reject", "reject"];
  }

  SMG_POLICY_REJECT {
    action = "reject";
    expression = "SMG_REJECTED";
    message = "message rejected by SentinelMail policy";
    require_action = ["no action", "add header", "rewrite subject", "greylist", "soft reject", "reject"];
  }

  SMG_TAG_REWRITE {
    action = "rewrite subject";
    expression = "SMG_TAGGED";
    subject = "Spam? %s";
    require_action = ["no action", "add header", "greylist"];
  }
}
